# Generated by Django 5.0.3 on 2024-04-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachmentor_app', '0005_course_book_link_course_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
