# Generated by Django 5.0.3 on 2024-04-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachmentor_app', '0010_useranswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='teachmentor_app.question'),
        ),
    ]
