# Generated by Django 5.0.3 on 2024-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachmentor_app', '0012_remove_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_ru',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
