# Generated by Django 5.0.3 on 2024-05-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachmentor_app', '0013_choice_text_en_choice_text_ru_course_course_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name_ru',
        ),
    ]
