# Generated by Django 5.0.3 on 2024-05-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachmentor_app', '0014_remove_course_course_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title_ru',
        ),
    ]
