# Generated by Django 5.0.3 on 2024-05-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachmentor_app', '0016_course_description_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
    ]
